# -*- coding: utf-8 -*-
"""prediksi_harga_beras

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sueK5ORuKBF0zUs_fbD3T7m4XjJ8q64Q
"""

import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from sklearn.linear_model import LinearRegression
import pickle

df = pd.read_csv("1762932136.csv")
df.columns = df.iloc[1]
df = df.drop([0,1]).reset_index(drop=True)

df.head()

df['Harga'] = (
    df['Harga']
    .astype(str)
    .str.replace('Rp', '', regex=False)
    .str.replace(',', '', regex=False)
    .str.replace('.', '', regex=False)
    .str.strip()
)

df['Harga'] = pd.to_numeric(df['Harga'], errors='coerce')
df = df.dropna(subset=['Harga'])
df['Harga'] = df['Harga'].astype(int)

df.info()

bulan_map = {
    'Januari': '01',
    'Februari': '02',
    'Maret': '03',
    'April': '04',
    'Mei': '05',
    'Juni': '06',
    'Juli': '07',
    'Agustus': '08',
    'September': '09',
    'Oktober': '10',
    'November': '11',
    'Desember': '12'
}

df['Tahun'] = df['Tahun'].astype(int)
df['Bulan_num'] = df['Bulan'].map(bulan_map)

df['Tanggal'] = pd.to_datetime(
    df['Tahun'].astype(str) + '-' + df['Bulan_num']
)

df.head()

df_beras = df[df['Komoditas'] == 'Beras Premium']
df_beras = df_beras.sort_values('Tanggal')

df_beras.head()

plt.figure(figsize=(10,5))
plt.plot(df_beras['Tanggal'], df_beras['Harga'])
plt.gca().xaxis.set_major_locator(mdates.YearLocator())
plt.gca().xaxis.set_major_formatter(mdates.DateFormatter('%Y'))
plt.title('Perkembangan Harga Beras Premium Nasional')
plt.xlabel('Tahun')
plt.ylabel('Harga (Rp)')
plt.grid(True)
plt.show()

df_beras['Index_Waktu'] = range(len(df_beras))

X = df_beras[['Index_Waktu']]
y = df_beras['Harga']

model = LinearRegression()
model.fit(X, y)

df_beras['Prediksi'] = model.predict(X)

plt.figure(figsize=(10,5))
plt.plot(df_beras['Tanggal'], df_beras['Harga'], label='Harga Aktual')
plt.plot(df_beras['Tanggal'], df_beras['Prediksi'], label='Garis Tren Model', linestyle='--')
plt.legend()
plt.title('Harga Aktual vs Garis Tren Linear')
plt.xlabel('Tanggal')
plt.ylabel('Harga (Rp)')
plt.grid(True)
plt.show()

tanggal_terakhir = df_beras['Tanggal'].max()
index_terakhir = df_beras['Index_Waktu'].max()

print("Data terakhir:", tanggal_terakhir.strftime("%B %Y"))

# ===== INPUT DARI USER =====
input_bulan = int(input("Masukkan bulan prediksi (1-12): "))
input_tahun = int(input("Masukkan tahun prediksi (contoh 2025): "))

selisih_bulan = (
    (input_tahun - tanggal_terakhir.year) * 12
    + (input_bulan - tanggal_terakhir.month)
)

if selisih_bulan < 0:
    print("Bulan & tahun yang dimasukkan sudah lewat dari data terakhir.")
else:
    index_prediksi = index_terakhir + selisih_bulan

    X_input = pd.DataFrame({'Index_Waktu': [index_prediksi]})
    hasil_prediksi = model.predict(X_input)

    print(
        f"Prediksi harga Beras Premium pada "
        f"{input_bulan:02d}-{input_tahun}: "
        f"Rp {int(hasil_prediksi[0])}"
    )

with open("model_harga_beras.pkl", "wb") as file:
    pickle.dump(model, file)

